# Generated by Django 4.1 on 2023-03-05 19:14

import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TinyUrl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tiny_url",
                    models.URLField(
                        editable=False, help_text="This is a Tiny URL", max_length=50
                    ),
                ),
                ("redirect_to", models.URLField()),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            2024, 3, 4, 19, 14, 25, 437752, tzinfo=datetime.timezone.utc
                        ),
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="tinyurl",
            constraint=models.UniqueConstraint(
                fields=("tiny_url",),
                name="tinyurls_tinyurl_unique_tiny_url",
                violation_error_message="Hey Bro this is not allowed. Tiny url must be unique!",
            ),
        ),
    ]
